server:
  port: @serviceUser.port@
  tomcat:
    max-threads: @serviceUser.threads@

eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka.hostname@:@eureka.port@/eureka/

spring:
  profiles:
    active: @package.env@
  application:
    name: service-user
  jackson:
    #去除json null字段
    default-property-inclusion: non_null
  datasource:
    url: @mysql.url@
    username: @mysql.username@
    password: @mysql.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  redis:
    host: @redis.host@
    port: @redis.port@
    database: @redis.database@
    password: @redis.password@

logging:
  path: @serviceUser.logpath@
  level:
    root: @log.level@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cm.service.user.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印全部sql