server:
  port: @service1.port@
  tomcat:
    max-threads: @service1.threads@

spring:
  profiles:
    active: @package.env@
  application:
    name: cm-service1
  jackson:
    #去除json null字段
    default-property-inclusion: non_null
#  datasource:
#    url: @mysql.url@
#    username: @mysql.username@
#    password: @mysql.password@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always

#  redis:
#    host: @redis.url@
#    port: @redis.port
#    database: @redis.database@
#    password: @redis.password@

logging:
  path: /my/logs/cm-cas-client1
  level:
    root: @log.level@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cm.cas.client1.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印全部sql